## Setup

In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

In [2]:
df = pd.read_csv('output/data.csv')
df

,AfterProbiotic,(12 or 13)-methylmyristate (a15:0 or i15:0),(14 or 15)-methylpalmitate (a17:0 or i17:0),(16 or 17)-methylstearate (a19:0 or i19:0),(3'-5')-adenylyladenosine*,(3'-5')-adenylylcytidine,(3'-5')-adenylyluridine,(3'-5')-cytidylylcytidine*,(3'-5')-cytidylylguanosine,(3'-5')-cytidylyluridine*,...,sedoheptulose,suberate (C8-DC),succinate,succinimide,threonate,tricarballylate,urate,xylose,mouseID,isMale
0,0,0.097699,0.031264,0.011751,0.002530,0.001595,0.002532,0.002700,0.001522,0.002641,...,0.040729,0.024735,0.347333,0.021981,0.155677,0.241432,0.048367,0.149068,1,1
1,1,0.158941,0.033450,0.010874,0.000659,0.000659,0.000659,0.000659,0.000659,0.001236,...,0.034188,0.042743,0.374643,0.033852,0.088292,0.078611,0.044431,0.180184,1,1
2,0,0.119596,0.034288,0.011585,0.001485,0.000785,0.001638,0.001818,0.000785,0.001973,...,0.060845,0.033103,0.286650,0.030653,0.116940,0.197009,0.045180,0.168328,2,1
3,1,0.130916,0.037041,0.015447,0.000921,0.000921,0.000921,0.000921,0.000921,0.000921,...,0.091777,0.035994,0.442962,0.022208,0.078139,0.105422,0.032510,0.140046,2,1
4,0,0.103788,0.037460,0.014543,0.002526,0.002436,0.002764,0.003566,0.000709,0.003389,...,0.034373,0.032385,0.286454,0.028730,0.195996,0.328468,0.057677,0.072740,3,1
5,1,0.154498,0.036943,0.014053,0.003345,0.002256,0.003578,0.003453,0.002385,0.003525,...,0.058926,0.044877,0.361670,0.031210,0.124713,0.139020,0.063091,0.093225,3,1
6,0,0.178249,0.040164,0.015899,0.003001,0.002235,0.003103,0.003046,0.000941,0.003117,...,0.021816,0.030599,0.344763,0.029454,0.153957,0.253468,0.063587,0.118900,4,0
7,1,0.111626,0.030752,0.011096,0.000832,0.000832,0.000832,0.000832,0.000832,0.000832,...,0.021584,0.033518,0.245637,0.020587,0.185380,0.159851,0.082961,0.101554,4,0
8,0,0.160207,0.038966,0.013056,0.002832,0.001893,0.003246,0.000934,0.000934,0.002383,...,0.026331,0.027682,0.240438,0.023459,0.121336,0.197046,0.052422,0.287363,5,0
9,1,0.129253,0.031197,0.011793,0.001061,0.001061,0.001061,0.003476,0.001061,0.003567,...,0.023904,0.030442,0.216346,0.024343,0.199169,0.174640,0.081636,0.055060,5,0

In [3]:
# run only if jupyterthemes installed

# import jtplot module in notebook
from jupyterthemes import jtplot
jtplot.style(theme='gruvboxd', context='paper', fscale=1.4, spines=False, 
             ticks=True, grid=True, figsize=(6, 4.5))

## Wilcoxon Signed-Rank Test

In [4]:
X_before = df.iloc[np.arange(0, 10, 2), 1:]
X_after = df.iloc[np.arange(1, 10, 2), 1:]
X_before.shape, X_after.shape

((5, 825), (5, 825))

In [5]:
X_before

,(12 or 13)-methylmyristate (a15:0 or i15:0),(14 or 15)-methylpalmitate (a17:0 or i17:0),(16 or 17)-methylstearate (a19:0 or i19:0),(3'-5')-adenylyladenosine*,(3'-5')-adenylylcytidine,(3'-5')-adenylyluridine,(3'-5')-cytidylylcytidine*,(3'-5')-cytidylylguanosine,(3'-5')-cytidylyluridine*,(3'-5')-guanylylcytidine,...,sedoheptulose,suberate (C8-DC),succinate,succinimide,threonate,tricarballylate,urate,xylose,mouseID,isMale
0,0.097699,0.031264,0.011751,0.002530,0.001595,0.002532,0.002700,0.001522,0.002641,0.002708,...,0.040729,0.024735,0.347333,0.021981,0.155677,0.241432,0.048367,0.149068,1,1
2,0.119596,0.034288,0.011585,0.001485,0.000785,0.001638,0.001818,0.000785,0.001973,0.001610,...,0.060845,0.033103,0.286650,0.030653,0.116940,0.197009,0.045180,0.168328,2,1
4,0.103788,0.037460,0.014543,0.002526,0.002436,0.002764,0.003566,0.000709,0.003389,0.003002,...,0.034373,0.032385,0.286454,0.028730,0.195996,0.328468,0.057677,0.072740,3,1
6,0.178249,0.040164,0.015899,0.003001,0.002235,0.003103,0.003046,0.000941,0.003117,0.002350,...,0.021816,0.030599,0.344763,0.029454,0.153957,0.253468,0.063587,0.118900,4,0
8,0.160207,0.038966,0.013056,0.002832,0.001893,0.003246,0.000934,0.000934,0.002383,0.000934,...,0.026331,0.027682,0.240438,0.023459,0.121336,0.197046,0.052422,0.287363,5,0

In [6]:
X_after

,(12 or 13)-methylmyristate (a15:0 or i15:0),(14 or 15)-methylpalmitate (a17:0 or i17:0),(16 or 17)-methylstearate (a19:0 or i19:0),(3'-5')-adenylyladenosine*,(3'-5')-adenylylcytidine,(3'-5')-adenylyluridine,(3'-5')-cytidylylcytidine*,(3'-5')-cytidylylguanosine,(3'-5')-cytidylyluridine*,(3'-5')-guanylylcytidine,...,sedoheptulose,suberate (C8-DC),succinate,succinimide,threonate,tricarballylate,urate,xylose,mouseID,isMale
1,0.158941,0.033450,0.010874,0.000659,0.000659,0.000659,0.000659,0.000659,0.001236,0.000659,...,0.034188,0.042743,0.374643,0.033852,0.088292,0.078611,0.044431,0.180184,1,1
3,0.130916,0.037041,0.015447,0.000921,0.000921,0.000921,0.000921,0.000921,0.000921,0.000921,...,0.091777,0.035994,0.442962,0.022208,0.078139,0.105422,0.032510,0.140046,2,1
5,0.154498,0.036943,0.014053,0.003345,0.002256,0.003578,0.003453,0.002385,0.003525,0.003142,...,0.058926,0.044877,0.361670,0.031210,0.124713,0.139020,0.063091,0.093225,3,1
7,0.111626,0.030752,0.011096,0.000832,0.000832,0.000832,0.000832,0.000832,0.000832,0.001177,...,0.021584,0.033518,0.245637,0.020587,0.185380,0.159851,0.082961,0.101554,4,0
9,0.129253,0.031197,0.011793,0.001061,0.001061,0.001061,0.003476,0.001061,0.003567,0.001061,...,0.023904,0.030442,0.216346,0.024343,0.199169,0.174640,0.081636,0.055060,5,0

In [16]:
import scipy
from math import inf

wilcoxon = pd.DataFrame(columns=['W_stat', 'p-value'])

# For each biochemical, perform the Wilcoxon Signed-Rank Test on the two classes: before and after probiotic. 
# Store values in wilcoxon
for biochem in range(823):
  X_before_biochem = X_before.iloc[:, biochem]
  X_after_biochem = X_after.iloc[:, biochem]
  # don't apply the test if the values are equal
  if (X_before_biochem.values == X_after_biochem.values).all():
    wilcoxon = wilcoxon.append({'W_stat' : inf, 'p-value' : 1.0}, ignore_index=True)
    continue
  result = scipy.stats.wilcoxon(X_before_biochem, X_after_biochem)
  wilcoxon = wilcoxon.append({'W_stat' : result.statistic, 'p-value' : result.pvalue}, ignore_index=True)
wilcoxon

     W_stat  p-value
0       7.0   1.0000
1       5.0   0.6250
2       4.0   0.4375
3       2.0   0.1875
4       1.0   0.1250
..      ...      ...
818     7.0   1.0000
819     6.0   0.8125
820     0.0   0.0625
821     4.0   0.4375
822     6.0   0.8125

[823 rows x 2 columns]

In [17]:
# print the biochemicals with p_value < 0.1 
crit = wilcoxon.loc[wilcoxon['p-value'] < 0.1]
crit

     W_stat  p-value
22      0.0   0.0625
23      0.0   0.0625
53      0.0   0.0625
64      0.0   0.0625
65      0.0   0.0625
..      ...      ...
790     0.0   0.0625
809     0.0   0.0625
814     0.0   0.0625
816     0.0   0.0625
820     0.0   0.0625

[125 rows x 2 columns]

### FDR correction

In [18]:
def BenjaminiHochberg(p_vals):
  """Returns p_vals after applying multiple hypothesis correction  
  using the Benjamini-Hochberg procedure"""
  ret = p_vals.copy()
  sorted_idx = np.argsort(p_vals)
  s = sorted(p_vals)
  last = s[-1]
  for i in range(len(p_vals) - 1, -1, -1):
    idx = sorted_idx[i]
    ret[idx] = min(last, s[i] * len(p_vals) / (i + 1))
    last = ret[idx]
    ret[idx] = round(ret[idx], 6)
  return ret

In [19]:
p_vals = wilcoxon['p-value'].to_numpy(copy=True)
p_vals[:10]

array([1.    , 0.625 , 0.4375, 0.1875, 0.125 , 0.1875, 0.625 , 0.625 ,
       0.4375, 0.3125])

In [20]:
p_vals_corrected = BenjaminiHochberg(p_vals)
p_vals_corrected[:10]

array([1.      , 0.940356, 0.825831, 0.61725 , 0.541447, 0.61725 ,
       0.940356, 0.940356, 0.825831, 0.7164  ])

In [21]:
wilcoxon['p-value'] = p_vals_corrected
wilcoxon

     W_stat   p-value
0       7.0  1.000000
1       5.0  0.940356
2       4.0  0.825831
3       2.0  0.617250
4       1.0  0.541447
..      ...       ...
818     7.0  1.000000
819     6.0  0.963527
820     0.0  0.411500
821     4.0  0.825831
822     6.0  0.963527

[823 rows x 2 columns]

In [22]:
wilcoxon.nsmallest(10, 'p-value')

    W_stat  p-value
22     0.0   0.4115
23     0.0   0.4115
53     0.0   0.4115
64     0.0   0.4115
65     0.0   0.4115
73     0.0   0.4115
74     0.0   0.4115
78     0.0   0.4115
80     0.0   0.4115
85     0.0   0.4115

There are no significant p-values after multiple hypothesis correction

##**Linear Model**##

For each biochemical, create a mixed effects linear model with mouseID as a random effect and gender and abundance as a fixed effect

In [129]:
! mkdir data

In [218]:
cleaned2

0  AfterProbiotic  (12 or 13)-methylmyristate (a15:0 or i15:0)  ...  mouseID  isMale
0               0                                       0.5460  ...        1       1
1               1                                       1.7082  ...        1       1
2               0                                       0.8329  ...        2       1
3               1                                       0.8805  ...        2       1
4               0                                       0.8143  ...        3       1
5               1                                       1.5794  ...        3       1
6               0                                       1.5593  ...        4       0
7               1                                       0.7600  ...        4       0
8               0                                       1.1195  ...        5       0
9               1                                       1.1442  ...        5       0

[10 rows x 826 columns]

In [157]:
for column in range(1, 824):
  df = cleaned2.iloc[:, [0, column, 824, 825]].copy()
  # change name of the biochem column to abundance
  df['abundance'] = df[df.columns[1]]
  df = df.drop(columns=[df.columns[1]])
  df.to_csv(cwd + "/data/%d.txt" % (column))

In [55]:
%load_ext rpy2.ipython

In [ ]:
%%R

install.packages("lme4",
   repos=c("http://lme4.r-forge.r-project.org/repos",
      getOption("repos")[["CRAN"]]))

library(lme4)

In [78]:
import rpy2.ipython.html
rpy2.ipython.html.init_printing()

In [178]:
%%R
p_vals = data.frame(
   p_val = c(1:823)
)
head(p_vals)

  p_val
1     1
2     2
3     3
4     4
5     5
6     6

In [195]:
%%R

get_p_val = function(data) {
    model = glmer(AfterProbiotic ~ (1|mouseID) + abundance + isMale, data=data, family=binomial)
    coef = coef(summary(model))[,4]
    p_val = coef[2]
    return (p_val)
}

In [ ]:
%%R
for (id in 1:823) {
  data = read.csv(file= paste("/content/data/", id, '.txt', sep=""))
  p_val = tryCatch(
      get_p_val(data),
      error=function(e) {return (1)}
  )
  p_vals[id, 1] = p_val
}

In [197]:
%%R
head(p_vals)

      p_val
1 0.3314071
2 0.7293395
3 0.8931477
4 0.4247669
5 0.4821257
6 0.4429726

In [198]:
%%R
write.csv(p_vals, "p_vals.csv")

In [201]:
p_vals = pd.read_csv("p_vals.csv")
p_vals

     Unnamed: 0     p_val
0             1  0.331407
1             2  0.729339
2             3  0.893148
3             4  0.424767
4             5  0.482126
..          ...       ...
818         819  0.148846
819         820  0.322706
820         821  0.984431
821         822  1.000000
822         823  0.319440

[823 rows x 2 columns]

In [203]:
p_vals.loc[p_vals['p_val'] < 0.05]

     Unnamed: 0     p_val
231         232  0.009317
292         293  0.049303

Two biochemicals have raw p values below 0.05

In [217]:
p_vals_numpy = p_vals.iloc[:, 1].to_numpy(copy=False)
p_vals_numpy = BenjaminiHochberg(p_vals_numpy)
p_vals_corrected = p_vals.copy()
p_vals_corrected.iloc[:, 1] = p_vals_numpy

In [215]:
p_vals_corrected.nsmallest(10, 'p_val')

    Unnamed: 0     p_val
23          24  0.750384
25          26  0.750384
26          27  0.750384
27          28  0.750384
28          29  0.750384
29          30  0.750384
30          31  0.750384
38          39  0.750384
42          43  0.750384
43          44  0.750384

There are no significant p values after correction